-- MySQL Script generated by MySQL Workbench
-- Tue Oct 28 19:46:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RoomBookingDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RoomBookingDB` DEFAULT CHARACTER SET utf8 ;
USE `RoomBookingDB` ;

-- -----------------------------------------------------
-- Table `RoomBookingDB`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoomBookingDB`.`Rooms` (
  `idRooms` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `buildingCode` CHAR(4) NOT NULL,
  `roomNumber` SMALLINT UNSIGNED NOT NULL,
  `roomSection` CHAR(2) NULL,
  `description` TEXT NULL,
  `accesLevel` TINYINT UNSIGNED NOT NULL,
  `capicity` INT UNSIGNED NOT NULL,
  `imageURL` VARCHAR(255) NULL,
  PRIMARY KEY (`idRooms`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `RoomBookingDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoomBookingDB`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `passwordHash` CHAR(60) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sessionKey` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `email` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `authorityLevel` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC), -- VISIBLE
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) -- VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `RoomBookingDB`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoomBookingDB`.`Bookings` (
  `idBookings` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `roomId` INT NOT NULL,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  `status` ENUM('PENDING', 'CONFIRMED', 'CANCELED') NOT NULL COMMENT 'e.g. pending, confirmed, canceled',
  `createdAt` DATETIME NULL,
  PRIMARY KEY (`idBookings`),
  INDEX `userId_idx` (`userId` ASC), -- VISIBLE
  INDEX `roomId_idx` (`roomId` ASC), -- VISIBLE
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `RoomBookingDB`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roomId`
    FOREIGN KEY (`roomId`)
    REFERENCES `RoomBookingDB`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `RoomBookingDB`.`Features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoomBookingDB`.`Features` (
  `idFeatures` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idFeatures`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) -- VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `RoomBookingDB`.`RoomFeatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoomBookingDB`.`RoomFeatures` (
  `idRoomFeatures` INT NOT NULL AUTO_INCREMENT,
  `roomId` INT NOT NULL,
  `featureId` INT NOT NULL,
  PRIMARY KEY (`idRoomFeatures`),
  INDEX `roomId_idx` (`roomId` ASC), -- VISIBLE
  INDEX `featureId_idx` (`featureId` ASC), -- VISIBLE
  CONSTRAINT `fk_room`
    FOREIGN KEY (`roomId`)
    REFERENCES `RoomBookingDB`.`Rooms` (`idRooms`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_feature`
    FOREIGN KEY (`featureId`)
    REFERENCES `RoomBookingDB`.`Features` (`idFeatures`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Default Rooms
INSERT INTO `RoomBookingDB`.`Rooms` (`name`, `buildingCode`, `roomNumber`, `roomSection`, `description`, `accesLevel`, `capicity`, `imageURL`)
VALUES
  ('Main Lecture Hall', 'MLH', 1, 'A', 'Big lecture hall for many people', 30, 90,'https://images.pexels.com/photos/269140/pexels-photo-269140.jpeg'),
  ('Science Building Lab', 'SC', 101, NULL,'Science Lab', 80, 50,'https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
  ('Library Study Room', 'LIB', 1, NULL, 'Quite Study Room', 40, 8,'https://images.unsplash.com/photo-1568667256549-094345857637?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
  ('Conference Room', 'ConR', 1, 'B','Conference room', 100, 20,'https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
  ('Arts Building Studio', 'Ar', 1, NULL, 'Quite Study Room', 50, 30,'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
  ('Computer Lab', 'CP', 3,NULL, 'Quite Study Room', 90, 40,'https://images.unsplash.com/photo-1547658719-da2b51169166?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  accesLevel = VALUES(accesLevel);

-- Default Users
INSERT INTO `RoomBookingDB`.`Users` 
  (`username`, `passwordHash`, `sessionKey`, `createdAt`, `email`, `authorityLevel`)
VALUES -- Passwords are hashed using bcrypt (admin password is 'admin', others are '123')
  ('admin', '$2b$12$uQv1HwrSRtXPS0c0dWezueP4O64tJXjAQlIVSa6OKZQjN2c3OIb0y', '', NOW(), 'admin@admin.com', 255),
  ('Mads', '$2b$12$.sxkbOcvmj7ltWBethRih.vPqyF5LsjkgYmZm1yzLU50nR4.LUNOC', '', NOW(), '6822808217@g.siit.tu.ac.th', 50),
  ('Julius', '2b$12$QHMELjUe.2UM4EGI/p/JiO8rXMirH32p1tM0SgjXuqE.tMtRDjKe6', '', NOW(), '6822808258@g.siit.tu.ac.th', 50),
  ('Anders', '$2b$12$UDyweEKOoxhOCHuljdnIde8jkid1NVzmvWERJC.SQv9mLZGL0kXQi', '', NOW(), '6822808209@g.siit.tu.ac.th', 50),
  ('Poramat', '$2b$12$opFrL7Mu970Hxrip7PqEBelYNDtw0AEjgM6D/CLjKe5lRlkFQfDku', '', NOW(), '6722800255@g.siit.tu.ac.th', 50),
  ('Chayanon', '$2b$12$I.sId4hAdF48uSkUdXquVOwGFOp5T2wPdfJYMZn9DukzYQWIY8Q7i', '', NOW(), '6522780426@g.siit.tu.ac.th', 50),
  ('Apichon', '$2b$12$//VlgjANnqBTHPYjNT/txuRBWcMY03M2EVHtaEmOCZ6Ap2omf1ppG', '', NOW(), 'apichon@siit.tu.ac.th', 100)
ON DUPLICATE KEY UPDATE
  email = VALUES(email),
  createdAt = VALUES(createdAt),
  authorityLevel = VALUES(authorityLevel);

-- Default Features
INSERT INTO `RoomBookingDB`.`Features` (`name`)
VALUES
  ('Projector'),
  ('Audio System'),
  ('Wheelchair Access'),
  ('Lab Equipment'),
  ('Whiteboard'),
  ('Quiet Zone'),
  ('Power Outlets'),
  ('Video Conferencing'),
  ('Catering Available'),
  ('Natural Light'),
  ('Art Supplies'),
  ('Flexible Seating'),
  ('30 Computers'),
  ('Software Suite')
ON DUPLICATE KEY UPDATE
  name = VALUES(name);

-- Default Room Features
-- -----------------------------------------------------
INSERT INTO `RoomBookingDB`.`RoomFeatures` (`roomId`, `featureId`)
VALUES 
  (1, 1), (1, 2), (1, 3), -- Main Lecture Hall
  (2, 4), (2, 1), (2, 5), -- Science Building Lab
  (3, 6), (3, 5), (3, 7), -- Library Study Room
  (4, 8), (4, 1), (4, 9), -- Conference Room
  (5, 10), (5, 11), (5, 12), -- Arts Building Studio
  (6, 13), (6, 1), (6, 14); -- Computer Lab